"""initial

Revision ID: 72e8c7785f28
Revises: 11e529978c9e
Create Date: 2026-08-07 16:29:17.202665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e8c7785f28'
down_revision: Union[str, Sequence[str], None] = '11e529978c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.create_index(op.f('ix_students_kana_name'), 'students', ['kana_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_kana_name'), table_name='students')
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    # ### end Alembic commands ###
