"""Add UserRole enum and replace is_editor

Revision ID: d07d115fce09
Revises: 72e8c7785f28
Create Date: 2026-08-18 15:14:07.948085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07d115fce09'
down_revision: Union[str, Sequence[str], None] = '72e8c7785f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = sa.Enum('STAFF', 'ADMIN', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('role', userrole, nullable=False, server_default='STAFF'))
    
    # Ma'lumotlarni o'tkazish
    op.execute("UPDATE users SET role = 'ADMIN' WHERE is_editor = true")
    
    op.drop_column('users', 'is_editor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_editor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
